debug: false #logback? debug log? ?? ? ??? ?? true??? ?? ?? ??? false
management:
  endpoints:
    web:
      exposure:
        include: "*"  #?????? endpoint ? ??? ??? ?? ??? ?? ?? ???? ?? ?? ???? ? ?????

logging:
  level:
    com.projectboard: debug
    org.springframework.web.servlet: debug  #debug: false ??? debug ???? ?? ???? ? ????...request response log? ???
    org.hibernate.type.descriptor.sql.BasicBinder: trace  #??? ?? jpa ??? ??? ? ?? log? debug log ? ????
                                                          #??? ?????? ? ? ????? ?? ? ? ?? ??

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: agh
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true #spring boot 2.4 or 2.5???? ?? ?? ?? ?? test? db ???? ?? ? ??
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true  #?? ????
    properties: #jpa ???? ?? ??? ????? ?? ? ?? ?? spring? ?????? ?? ???? ?? ???? ?? ????
      hibernate.format_sql: true #??? ??? ?? ???? ??? ? ? ?? ??
      hibernate.default_batch_fetch_size: 100 #jpa?? ????? ??? ??? ?? ? ??? ??? ? ??? ???
  sql.init.mode: always # ?? ??????? 3?? ??? ??? always? ?? db? ???? test???? ???? ????

#---
## ? ? 3?? ???? ??? ??? ?? ??? ??? ???
##? document ?? ?? ?? profile ?? ??
#spring:
#  config.activate.on-profile: testdb
#  datasource: #testdb? ???? ?? datasource ? ????? ? ??
#    url: jdbc:h2:mem:board;mode=mysql #mode ? mysql ??? ???
#    driverClassName: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none #? ??? ???? ???? ??? db ?? ?? ??? ? testdb ? ???? ?? ???
#

